//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 07:55:10 PM CDT 
//


package generatedPost;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generatedPost package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generatedPost
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link Library.LibraryBooks }
     * 
     */
    public Library.LibraryBooks createLibraryLibraryBooks() {
        return new Library.LibraryBooks();
    }

    /**
     * Create an instance of {@link Library.LibraryBooks.Authors }
     * 
     */
    public Library.LibraryBooks.Authors createLibraryLibraryBooksAuthors() {
        return new Library.LibraryBooks.Authors();
    }

    /**
     * Create an instance of {@link Library.Librarians }
     * 
     */
    public Library.Librarians createLibraryLibrarians() {
        return new Library.Librarians();
    }

    /**
     * Create an instance of {@link Library.LibraryBooks.Authors.Author }
     * 
     */
    public Library.LibraryBooks.Authors.Author createLibraryLibraryBooksAuthorsAuthor() {
        return new Library.LibraryBooks.Authors.Author();
    }

}
